---

- name: Create the Github SSH public key file
  copy: src="~/.ssh/id_rsa.pub"
        dest="/root/.ssh/id_rsa.pub"
        mode=0644

- name: Create the Github SSH private key file
  copy: src="~/.ssh/id_rsa"
        dest="/root/.ssh/id_rsa"
        mode=0600

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ project_path }}
       accept_hostkey=True
       key_file="/root/.ssh/id_rsa"
  when: setup_git_repo is defined and setup_git_repo
  tags: git

# - name: Setup the Git repo
#   git: repo={{ git_repo }}
#        version={{ git_branch }}
#        dest={{ project_path }}
#        accept_hostkey=yes
# Known_hosts Custom Module
#   known_hosts: path='~/.ssh/known_hosts'
#         name='id_rsa'
#         key="{{ lookup('file', '~/.ssh/id_rsa') }}"

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
